# Generated by Django 3.1.4 on 2021-01-15 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.IntegerField(max_length=10)),
                ('city', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=45)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CurierList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=30)),
                ('rcontact', models.IntegerField(max_length=10)),
                ('pick_up_address', models.CharField(max_length=40)),
                ('delivery_address', models.CharField(max_length=40)),
                ('pweight', models.IntegerField(max_length=5)),
                ('plength', models.IntegerField(max_length=5)),
                ('pwidth', models.IntegerField(max_length=5)),
                ('pheight', models.IntegerField(max_length=5)),
                ('delivery_service', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
