# Generated by Django 3.1.4 on 2021-01-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curierlist',
            name='pheight',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='curierlist',
            name='plength',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='curierlist',
            name='pweight',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='curierlist',
            name='pwidth',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='curierlist',
            name='rcontact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='signup',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
